version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0

  pre_build:
    commands:
      - echo Restore started on `date`
      - echo "CURRENT DIR `pwd`"
      - dotnet restore StreamApp2/UMS.API2.csproj

  build:
    commands:
      - echo Build started on `date`
      - dotnet build StreamApp2/UMS.API2.csproj

  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish -c Release -o ./build-output StreamApp2/UMS.API2.csproj

artifacts:
  name: DEMO_API_Build_#$CODEBUILD_BUILD_NUMBER
  base-directory: './build-output'
  files:
    - ./**/*