version: 0.2

phases:
  install:
    commands:
      - echo Installing .NET Core 8.0 SDK
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 8.0  # Install .NET 8.0 SDK
      - export PATH="$PATH:$HOME/.dotnet"
      - export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true  # Disable globalization
      - dotnet --version  # Verify the SDK installation
  pre_build:
    commands:
      - echo Restoring NuGet packages
      - dotnet restore  # Restore dependencies
  build:
    commands:
      - echo Building the project
      - dotnet build --configuration Release  # Build the project in Release mode
  post_build:
    commands:
      - echo Running tests
      - dotnet test --no-build --verbosity normal  # Optional: Run tests

artifacts:
  files:
    - '**/*'
    - '!**/*.pdb'
  discard-paths: yes
